language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - PUBLIC_PATH=/slides-chrome-devtools/ npm run build
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"